; Manual Transmission for GTA V
; Please refer to the readme or the in-game menu for option descriptions
; Please use the in-game menu to configure the mod


[MT_OPTIONS]
EnableWheel = true
LogitechLEDs = false
HPatternKeyboard = false
UseShifterForAuto = false


[FORCE_FEEDBACK]
Enable = true
SATAmpMult = 1.000000
DamperMax = 100
DamperMin = 40
DamperMinSpeed = 6.400000
DetailMult = 4.000000
DetailLim = 5000
DetailMaw = 3
CollisionMult = 2.500000
AntiDeadForce = 0
FFBProfile = 0
ResponseCurve = 1.000000
SlipOptMin = 7.500000
SlipOptMinMult = 1.600000
SlipOptMax = 25.000000
SlipOptMaxMult = 1.000000
SATFactor = 0.800000
Gamma = 0.750000
MaxSpeed = 80.000000


[INPUT_DEVICES]
DEV0 = PXN V10 Pro
GUID0 = {8A8229C0-BD68-11F0-8001-444553540000}


[STEER]
ANTIDEADZONE = 0.250000
DEADZONE = 0.000000
DEADZONEOFFSET = 0.000000
SteerAngleMax = 900.000000
SteerAngleCar = 900.000000
SteerAngleBike = 180.000000
SteerAngleBoat = 360.000000
GAMMA = 1.000000
DEVICE = 0
AXIS = lX
MIN = 0
MAX = 65535
FFB = lX


[THROTTLE]
GAMMA = 1.000000
ANTIDEADZONE = 0.250000
DEVICE = 0
AXIS = lZ
MIN = 0
MAX = 65535


[BRAKE]
GAMMA = 1.000000
ANTIDEADZONE = 0.250000
DEVICE = 0
AXIS = lRz
MIN = 0
MAX = 65535


[CLUTCH]
DEVICE = 0
AXIS = rglSlider0
MIN = 0
MAX = 65535


[AUTO_P]
DEVICE = -1
BUTTON = -1


[AUTO_R]
DEVICE = -1
BUTTON = -1


[AUTO_N]
DEVICE = -1
BUTTON = -1


[AUTO_D]
DEVICE = -1
BUTTON = -1


[SHIFT_UP]
DEVICE = 0
BUTTON = 5


[SHIFT_DOWN]
DEVICE = 0
BUTTON = 4


[CLUTCH_BUTTON]
DEVICE = 0
BUTTON = 12


[LIGHTS]
DEVICE = 0
BUTTON = 8


[LOOK_BACK]
DEVICE = 0
BUTTON = 18000


[LOOK_LEFT]
DEVICE = 0
BUTTON = 27000


[LOOK_RIGHT]
DEVICE = 0
BUTTON = 9000


[INDICATOR_LEFT]
DEVICE = 0
BUTTON = 6


[INDICATOR_RIGHT]
DEVICE = 0
BUTTON = 7
